import Head from 'next/head'
import Image from 'next/image'
import { GetServerSideProps } from 'next/types'

import { productsQuery } from '@shopify/queries/productsQuery'
import { shopifyClient } from '@shopify/client'
import { Product, Entities } from '@shopify/schema'

import ProductGrid from '@components/product/ProductGrid/ProductGrid'

type ProductsResultType = {
  products?: Entities<Product>
}

export const getServerSideProps: GetServerSideProps = async () => {
  const productsResult = await shopifyClient.request<ProductsResultType>(
    productsQuery
  )

  return {
    props: {
      productsResult: productsResult.products
    }
  }
}

type HomePageProps = {
  productsResult?: Entities<Product>
}

const HomePage = ({ productsResult }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="imageWrapper relative">
          <Image
            src="/mock-carousel-image.webp"
            alt=""
            width={500}
            height={500}
          />
        </div>
        {productsResult ? (
          <div className="bg-[#ffffff] py-8 px-4 md:py-[72px] md:px-12">
            <div className="mx-auto">
              <h2 className="text-[22px] md:text-[28px] text-center">
                Winter Collection
              </h2>

              <ProductGrid
                products={productsResult?.edges.map(item => item.node)}
              />
            </div>
          </div>
        ) : null}
      </div>
    </>
  )
}

export default HomePage
