import Head from 'next/head'
import Link from 'next/link'
import { GetServerSideProps } from 'next/types'

import { productsQuery } from '@shopify/queries/productsQuery'
import { shopifyClient } from '@shopify/client'
import { Product, Entities } from '@shopify/schema'

type ProductsResultType = {
  products?: Entities<Product>
}

export const getServerSideProps: GetServerSideProps = async () => {
  const productsResult = await shopifyClient.request<ProductsResultType>(
    productsQuery
  )

  return {
    props: {
      productsResult: productsResult.products
    }
  }
}

type HomePageProps = {
  productsResult?: Entities<Product>
}

const HomePage = ({ productsResult }: HomePageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {productsResult?.edges.map(({ node }) => (
          <Link key={node.id} href={`/product/${node.handle}`}>
            <h2>
              {node.title} <span>-&gt;</span>
            </h2>
            <p>{node.description}</p>
          </Link>
        ))}
      </div>
    </>
  )
}

export default HomePage
